language: php

php:
  - 7.4.0
  - 7.4.1
  - 7.4

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - xdebug=yes

cache:
  files:
    - ./.php_cs.cache
    - ./.phpunit.result.cache
  directories:
    - $HOME/.composer/cache

before_script:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist

script:
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/phpunit --coverage-clover=./phpunit.clover && ./vendor/bin/php-coveralls --no-interaction -vvv && ./vendor/bin/infection --min-msi=100; else ./vendor/bin/phpunit --no-coverage; fi
  - if [[ "$xdebug" != "yes" ]]; then composer run static-analysis; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/psalm --shepherd --show-info=false; else ./vendor/bin/psalm --show-info=false; fi
  - if [[ "$xdebug" != "yes" ]]; then composer update --dry-run roave/security-advisories; fi

after_script:
  - if [[ "$xdebug" = "yes" ]]; then cat infection.log; fi
